### ISSUE TITLE
【ToDo】追加・修正リスト

### ISSUE THREAD

**Issue by yuminishi0309** [yuminishi0309/mavs-task-wp#12]
追加・修正点リスト

### ほか
- [x] All-in-One WP Migration

### 共通
- [x] READ MOREボタンのアニメーション変更
- [ ] アニメーションのspeed、transitionはなるべく統一（MV、ボタン、スライダー等のスピード感を合わせる）

### header
- [x] SP fadeInメニュー　独立ボタン内の文字を左右中心に（左に寄っている）
- [x] gnavメニュー文字サイズ確認（小さく見える）
- [x] header/footer gnavホバーアニメーションの文字サイズとライン長さを合わせる
- [x] header/footer 四角ボタンのホバー（右に抜けるように）

### footer
- [x] グレーの装飾が画面幅wideで崩れる

### top
- [x] トップページアニメーション（仮）（画像などの要素出現）
- [x] 修正：上記タイミング等
- [x] MV 回転するロゴの位置もう少し上
- [x] MV キャッチフレーズの位置設定方法変更
- [x] セクションの背景画像アニメーションで（グレーとカラー分離）
- [x] member-sec 画像位置修正（左端はみ出ている）
- [ ] service/member-sec 背景と画像分離してアニメーション
- [x] blog-sec スライダー速度
- [x] blog-sec 記事カードホバー設定
- [x] blog-sec 記事カード内pic/txt間の余白
- [x] blog-sec サブタイトルの位置確認
- [x] banner ホバー設定（可能なら分離）
- [ ] ↑動き追加
- [x] news-sec ホバー設定変更（動きのないものにする）
- [x] news-sec aクリック範囲狭い
- [x] news-sec タイトル2段になることがある
- [ ] MV場面転換アニメーション（工数次第）

### blog
- [x] カテゴリのトグルメニュー記号の角度
- [x] カテゴリトグルメニュー「CATEGORY」文字が小さい
- [x] ページネーション　カレントページの色変更
- [x] ページネーション1の位置左に寄っているのでボタン幅伸ばして調整
- [x] 記事カードのホバーアニメーション
- [x] PREV/NEXT外れた時の位置(PREVがない時のNEXTの位置)
- [x] 記事数が3列ない場合のスタイル修正 PC版（一覧/カテゴリ一覧ページ）
- [x] 各投稿slug名
- [ ] tableの線色をグレーにする
- [ ] サンプル記事：テキストの文字サイズ,marginを調整（フォントサイズはcssで上書き）

### contact
- [x] チェックボックス小さい
- [x] トグルやテキストboxのpadding設定（左狭い）
- [x] inputのsample文字色が濃い→薄く設定
- [x] input,textarea,checkbox, radioの枠線の「線幅と色」を全状況で統一（例外：文字入力時の枠線色がマゼンダ）
- [x] radioの黒点の大きさ（小さくする）
- [x] checkboxの箱の線色と線幅の調整
